app/views/categories.py
"""wiew for showing all categories with their jokes """
from flask import Blueprint, redirect, render_template
from flask_paginate import Pagination

from app.models import Category
from config import PAGINATION_FRAMEWORK, PER_PAGE

CATEGORIES_MOD = Blueprint('categories', __name__)
@CATEGORIES_MOD.route('/')
def index():
    """index page where are showen all categories"""
    categories = Category.query.all()
    return render_template('categories/index.html',
                           categories=categories, head_name='Kategórie vtipov')
@CATEGORIES_MOD.route('/<name>', defaults={'page': 1})
@CATEGORIES_MOD.route('/<name>/', defaults={'page': 1})
@CATEGORIES_MOD.route('/<name>/page/<page>')
@CATEGORIES_MOD.route('/<name>/page/<page>/')

def category(name, page=1):
    """specific category page with all its jokes"""
    current_category = Category.query.filter_by(name=name).first()
    if current_category is None:
        return redirect('/kategorie')
    try:
        page = int(page)
    except ValueError:
        return redirect('kategorie/' + name)
    jokes = current_category.jokes.order_by('rank desc').limit(PER_PAGE).offset((page - 1) * PER_PAGE).all()
    total = current_category.jokes.count()
    pagination = Pagination(page=page,
                            css_framework=PAGINATION_FRAMEWORK,
                            PER_PAGE=PER_PAGE,
                            total=total,
                            format_total=True,
                            format_number=True,
                           )
    return render_template('categories/category.html',
                           category=current_category,
                           jokes=jokes,
                           pagination=pagination,
                           head_name=current_category.name
                          )

app/templates/categories/category.html
<!-- extend base layout -->
{% extends "base.html" %} 
{% block head %}<link rel="stylesheet" href="{{ url_for('static', filename='css/reaction.css') }}"> {% endblock %}
{% block content %}
{%for joke in jokes%}
<div class="col-md-12 col-sm-12">
  <div class="card card-nav-tabs joke">
    <div class="content">
      <div class="tab-content">
        <div class="tab-pane active">
         {% include "components/joke.html" %}
          <!-- <span class="sharing-area"><button class="btn btn-facebook facebook-share"><i class="fa fa-facebook"></i></button></span>
          <button class="btn btn-info play-voice-api"><i class="fa fa-volume-up"></i></button> -->
        </div>
      </div>
    </div>
  </div>
</div>
{%endfor%}
<div class="clear-fix"></div>
<div class="text-center"> {{ pagination.links }}</div>
{% endblock %} 
{%block scripts%}
<script src="http://code.responsivevoice.org/responsivevoice.js"></script>
<script src="{{ url_for('static', filename='js/controllers/add_joke_reaction.js') }}"></script>
<script>
  $(".play-voice-api").click(function () {
    responsiveVoice.speak($(this).prev('p').text(), "Slovak Female");
  });
</script>

{%endblock%}

app/templates/categories/index.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
{%for category in categories%}
   <div class="col-md-4 col-sm-12">
							<div class="card card-nav-tabs">
								<div class="header header-primary">
									<div class="nav-tabs-navigation">
										<div class="nav-tabs-wrapper">
											<ul class="nav nav-tabs" data-tabs="tabs">
												<li class="active">
													<a href="{{ url_for('categories.category', name=category.name) }}">
														<i class=""></i>
														{{category.name}}
														<div class="ripple-container"></div>
													</a>
												</li>
											</ul>
										</div>
									</div>
								</div>

							</div>
						</div>
{%endfor%}
{% endblock %}