app/views/categories.py
"""wiew for showing all categories with their jokes """
from flask import Blueprint, redirect, render_template
from flask_paginate import Pagination

from app.models import Category
from config import PAGINATION_FRAMEWORK, PER_PAGE

CATEGORIES_MOD = Blueprint('categories', __name__)
@CATEGORIES_MOD.route('/')
def index():
    """index page where are showen all categories"""
    categories = Category.query.all()
    return render_template('categories/index.html',
                           categories=categories, head_name='Kategórie vtipov')
@CATEGORIES_MOD.route('/<name>', defaults={'page': 1})
@CATEGORIES_MOD.route('/<name>/', defaults={'page': 1})
@CATEGORIES_MOD.route('/<name>/page/<page>')
@CATEGORIES_MOD.route('/<name>/page/<page>/')

def category(name, page=1):
    """specific category page with all its jokes"""
    current_category = Category.query.filter_by(name=name).first()
    if current_category is None:
        return redirect('/kategorie')
    try:
        page = int(page)
    except ValueError:
        return redirect('kategorie/' + name)
    jokes = current_category.jokes.order_by('rank desc').limit(PER_PAGE).offset((page - 1) * PER_PAGE).all()
    total = current_category.jokes.count()
    pagination = Pagination(page=page,
                            css_framework=PAGINATION_FRAMEWORK,
                            PER_PAGE=PER_PAGE,
                            total=total,
                            format_total=True,
                            format_number=True,
                           )
    return render_template('categories/category.html',
                           category=current_category,
                           jokes=jokes,
                           pagination=pagination,
                           head_name=current_category.name
                          )

app/views/jokes.py
""" view for showing all jokes and unique jokes """
import logging
from flask import Blueprint, redirect, render_template, request, json
from flask_paginate import Pagination
from flask_login import current_user

from app.models import Joke
from app.models import ReactionsType
from config import PAGINATION_FRAMEWORK, PER_PAGE

JOKES_MOD = Blueprint('jokes', __name__)
LOGGER = logging.getLogger("backend")

@JOKES_MOD.route('/', defaults={'page': 1})
@JOKES_MOD.route('/page/<page>')
@JOKES_MOD.route('/page/<page>/')
def index(page):
    """index page where all jokes are showed ordered by rank """
    try:
        page = int(page)
    except ValueError:
        return redirect('/')
    jokes = Joke.query.order_by('rank desc').limit(PER_PAGE).offset((page - 1) * PER_PAGE).all()
    total = Joke.query.count()
    pagination = Pagination(page=page,
                            css_framework=PAGINATION_FRAMEWORK,
                            PER_PAGE=PER_PAGE,
                            total=total,
                            format_total=True,
                            format_number=True,
                           )
    return render_template('jokes/index.html',
                           jokes=jokes, pagination=pagination)

@JOKES_MOD.route('/<joke_id>')
def joke(joke_id):
    """view for one specific joke"""
    current_joke = Joke.query.filter_by(id=joke_id).first()
    return render_template('jokes/joke.html',
                           joke=current_joke)

@JOKES_MOD.route('/rate-joke', methods=['POST'])
def rate_joke():
    """add new reaction to database"""
    joke_id = request.form["joke_id"]
    reaction_id = request.form["reaction_id"]
    try:
        reaction_id = int(reaction_id)
    except:
        LOGGER.error("reaction id is not an integer: ", reaction_id)
        return json.dumps({'status': False})

    try:
        joke_id = int(joke_id)
    except:
        LOGGER.error("joke id is not an integer: ", reaction_id)
        return json.dumps({'status': False})

    try:
        reaction = ReactionsType(reaction_id)
    except Exception as e:
        LOGGER.error("not found reaction id in ReactionsType enum ", str(e))
        return json.dumps({'status': False})
    
    current_joke = Joke.query.filter_by(id=joke_id).first()
    if not current_joke:
        LOGGER.error("joke not found")
        return json.dumps({'status': False})
    
    try:
        user_id = current_user.id
    except:
        user_id = 0
    current_joke.add_reaction(reaction, user_id)
    return json.dumps({'status': True, 'data':current_joke.order_reactions()})
    

app/templates/auth.html
<html>

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="">
    <link rel="icon" type="image/png" href="assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Vtipy starej matere</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/material-kit.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/demo.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-notify.css') }}"> {%block head%}{%endblock%}
</head>

<body class="signup-page">
    <!-- Navbar -->
    {% include "menu.html" %}
    <!-- End Navbar -->

    <div class="wrapper">
        <div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&'); background-size: cover; background-position: top center;">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                        <div class="card card-signup">
                            {% block content%}{%endblock%}     
                        </div>
                    </div>
                </div>
            </div>
         {%include "footer.html" %}

        </div>
    </div>

    <!--   Core JS Files   -->
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/material.min.js') }}" type="text/javascript"></script>



    <!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
    <script src="{{ url_for('static', filename='js/material-kit.js') }}" type="text/javascript"></script>

    <!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
    <script src="{{ url_for('static', filename='js/bootstrap-datepicker.js') }}" type="text/javascript"></script>

    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="{{ url_for('static', filename='js/nouislider.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-notify.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/initial.js') }}" type="text/javascript"></script>
    {%block scripts%}{%endblock%}
</body>

</html>

app/templates/base.html
<html>

<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="">
	<link rel="icon" type="image/png" href="assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Vtipy starej matere</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

	<!--     Fonts and icons     -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	<!-- CSS Files -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/material-kit.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/demo.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-notify.css') }}">

	{%block head%}{%endblock%}
</head>

<body class="components-page">
	<!-- Navbar -->
	{% include "menu.html" %} 
	<!-- End Navbar -->

	<div class="wrapper">
		<div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&h=750&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450');">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<h1 class="title text-center">{% block title %}{{head_name|default}}{% endblock title %}</h1>
					</div>
				</div>
			</div>
		</div>

		<div class="main main-raised">
			<div class="section section-tabs">
				<div class="container">
					{%block content%}{%endblock%}
				</div>
			</div>
		</div>
	{%include "footer.html" %}
	</div>

	<!--   Core JS Files   -->
	<script src="{{ url_for('static', filename='js/jquery.min.js') }}" type="text/javascript"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" type="text/javascript"></script>
	<script src="{{ url_for('static', filename='js/material.min.js') }}" type="text/javascript"></script>



	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
	<script src="{{ url_for('static', filename='js/material-kit.js') }}" type="text/javascript"></script>

	<!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
	<script src="{{ url_for('static', filename='js/bootstrap-datepicker.js') }}" type="text/javascript"></script>

	<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
	<script src="{{ url_for('static', filename='js/nouislider.min.js') }}" type="text/javascript"></script>
	<script src="{{ url_for('static', filename='js/bootstrap-notify.min.js') }}" type="text/javascript"></script>
	<script src="{{ url_for('static', filename='js/initial.js') }}" type="text/javascript"></script>
	{%block scripts%}{%endblock%}
</body>

</html>

app/templates/footer.html
<footer class="footer">
			<div class="container">
				<nav class="pull-left">
					<ul>
						<li>
							<a href="{{ url_for('categories.index') }}">
							Kategórie
						</a>
						</li>
						<li>
							<a href="http://presentation.creative-tim.com">
						   Top vtipy
						</a>
						</li>
						<li>
							<a href="http://blog.creative-tim.com">
						   Galéria vtipov
						</a>
						</li>
						<li>
							<a href="http://www.creative-tim.com/license">
							Smiech nikdy nespí
						</a>
						</li>
					</ul>
				</nav>
				<div class="copyright pull-right">
					&copy; 2016, Túto webovú stránku sme vytvorili so <i class="material-icons">favorite</i> Váš AppoxideLab
				</div>
			</div>
		</footer>

app/templates/menu.html
<nav class="navbar navbar-transparent navbar-fixed-top navbar-color-on-scroll">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
	        	<span class="sr-only">Toggle navigation</span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	    	</button>
			<a class="navbar-brand" href="/">Smútok neexistuje &nbsp {% if category%}( {{category.name}} ){%endif%}<div class="ripple-container"></div></a>
		</div>

		<div class="collapse navbar-collapse" id="navigation-index">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a href="{{ url_for('categories.index') }}">
						<i class="material-icons">toc</i> Kategórie
					</a>
				</li>
				<li>
					<a href="{{ url_for('jokes.index') }}">
						<i class="material-icons">grade</i> Najlepšie vtipy
					</a>
				</li>
				<li>
					<a href="{{ url_for_security('login') }}">
						<i class="material-icons">person</i> {{_("Prihlásenie")}}
					</a>
				</li>
				<li>
					<a href="{{ url_for_security('register') }}">
						<i class="material-icons">people</i> {{_("Registrácia")}}
					</a>
				</li>
				<li>
					<a rel="tooltip" title="Sleduj nás na Twittri" data-placement="bottom" href="https://twitter.com/CreativeTim" target="_blank"
					    class="btn btn-white btn-simple btn-just-icon">
						<i class="fa fa-twitter"></i>
					</a>
				</li>
				<li>
					<a rel="tooltip" title="Lajkni náš FB" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank"
					    class="btn btn-white btn-simple btn-just-icon">
						<i class="fa fa-facebook-square"></i>
					</a>
				</li>
				<li>
					<a rel="tooltip" title="Sleduj nás na Insta" data-placement="bottom" href="https://www.instagram.com/CreativeTimOfficial"
					    target="_blank" class="btn btn-white btn-simple btn-just-icon">
						<i class="fa fa-instagram"></i>
					</a>
				</li>

			</ul>
		</div>
	</div>
</nav>